### ISSUE TITLE
 Need dll without ssl support

### ISSUE THREAD

**Issue by ZakharYA** [FredyH/GWSockets#20]
Hello!
My hosting does not support SSL in Linux, and I do not understand C ++.
So when I try to `require("gwsockets")` I get an error.
Could you add a non-ssl version to the release?

**Comment by FredyH** [comment]
The library already comes with SSL, you do not need it.
Ask your host why the library does not work.

**Comment by ZakharYA** [comment]
As it turned out, my hosting uses CentOS.
As I understood from your last commit, CentOS is not supported and needs to be compiled for it. But unfortunately I have no experience in this.

**Comment by FredyH** [comment]
Alright so I just tested it and it works on CentOS 8 while it does not work on CentOS 7.
CentOS 7 is using glibc from 2014 and I am not willing to support a library that old and there is no reason to use CentOS for hosting game servers anyways.
So I suggest that you tell your server host to upgrade to either CentOS 8 or use a distro that is generally more up to date (Debian, Ubuntu, Fedora).
Event CentOS 8 will still have the problem of not finding the SSL root certificates because it is in a location the included libssl can not find, so even then you will have to set verifyCertificate to false when creating the websocket, which will make you vulnerable to man-in-the-middle attacks though.

I should probably add a function for setting the path to the root certificates in the next release or so, so I will keep that in mind.
