### ISSUE TITLE
Failing websocket handshake with case-sensitive header value

### ISSUE THREAD

**Issue by robilkot** [FredyH/GWSockets#38]
While performing websocket handshake with server, client sends header 'Connection' with value 'upgrade' instead of 'Upgrade'. Since values are case-sensitive, protocol switching may not be performed depending on server-side request processing (faced this issue while working with https://github.com/gilmaimon/ArduinoWebsockets). In comparison, Postman sends value 'Upgrade' and everything works just fine

**Comment by FredyH** [comment]
You are right that header values _can_ be case sensitive. It is not our library that handles the upgrading of the HTTP connection, so we do not have access to change the case sensitivity.
However, it seems like sending `upgrade` rather than `Upgrade` should work according to the standard, see the first example [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Protocol_upgrade_mechanism).

In fact, the [specification ](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Connection) of the `Connection` header only specifies values in lower case.

**Comment by robilkot** [comment]
Thanks for the answer. Interestingly, mdn also provides examples with upper-case 'Upgrade' [here](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers) and down the link you sent
